/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SlotObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SlotParameters struct {

	// Which database to create the replication slot on. Defaults to provider database.
	// Sets the database to add the replication slot to
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// Sets the output plugin.
	// Sets the output plugin to use
	// +kubebuilder:validation:Required
	Plugin *string `json:"plugin" tf:"plugin,omitempty"`
}

// SlotSpec defines the desired state of Slot
type SlotSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SlotParameters `json:"forProvider"`
}

// SlotStatus defines the observed state of Slot.
type SlotStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SlotObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Slot is the Schema for the Slots API. Creates and manages a replication slot on a PostgreSQL server.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,postgresql}
type Slot struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SlotSpec   `json:"spec"`
	Status            SlotStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SlotList contains a list of Slots
type SlotList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Slot `json:"items"`
}

// Repository type metadata.
var (
	Slot_Kind             = "Slot"
	Slot_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Slot_Kind}.String()
	Slot_KindAPIVersion   = Slot_Kind + "." + CRDGroupVersion.String()
	Slot_GroupVersionKind = CRDGroupVersion.WithKind(Slot_Kind)
)

func init() {
	SchemeBuilder.Register(&Slot{}, &SlotList{})
}
